/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.Box;
import model.domain.AdminModel;

/**
 *
 * @author lgpc1
 */
public class ViewMain extends javax.swing.JFrame {
    /*
    * Custom Variables
    */
    ViewMidiaHomeJumbotron viewJumbotron = null;
    /**
     * Creates new form ViewMain
     */
    
    public ViewMain() {
        initComponents();
    }

    public ViewMain(AdminModel userData) {
        initComponents();
        this.setVisible(true);
        /*
        *Layout Modify
        */
        menuBar.add(Box.createHorizontalGlue());
        menuBar.add(menuUsuario);
        
        /*
        *Info Handling
        */
        String nomeUsuario = userData.getUsuario().substring(0, 1).toUpperCase() + userData.getUsuario().substring(1);
        menuUsuario.setText(nomeUsuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        menuMidia = new javax.swing.JMenu();
        menuMidiaHome = new javax.swing.JMenu();
        midiaHomeJumbotron = new javax.swing.JMenuItem();
        midiaHomeCarrossel = new javax.swing.JMenuItem();
        midiaHomeGaleria = new javax.swing.JMenuItem();
        menuCadastrar = new javax.swing.JMenu();
        menuCadastrarAdministrador = new javax.swing.JMenuItem();
        menuCadastrarAluno = new javax.swing.JMenuItem();
        menuUsuario = new javax.swing.JMenu();
        menuUsuarioConta = new javax.swing.JMenu();
        menuUsuarioSair = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuMidia.setMnemonic('f');
        menuMidia.setText("Mídia");

        menuMidiaHome.setText("Página Home");

        midiaHomeJumbotron.setText("Jumbotron");
        midiaHomeJumbotron.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                midiaHomeJumbotronActionPerformed(evt);
            }
        });
        menuMidiaHome.add(midiaHomeJumbotron);

        midiaHomeCarrossel.setText("Carrossel");
        menuMidiaHome.add(midiaHomeCarrossel);

        midiaHomeGaleria.setText("Galeria");
        menuMidiaHome.add(midiaHomeGaleria);

        menuMidia.add(menuMidiaHome);

        menuBar.add(menuMidia);

        menuCadastrar.setText("Cadastrar");
        menuCadastrar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                menuCadastrarItemStateChanged(evt);
            }
        });

        menuCadastrarAdministrador.setText("Administrador");
        menuCadastrarAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarAdministradorActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuCadastrarAdministrador);

        menuCadastrarAluno.setText("Aluno");
        menuCadastrarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarAlunoActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuCadastrarAluno);

        menuBar.add(menuCadastrar);

        menuUsuario.setText("User");
        menuUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        menuUsuarioConta.setText("Conta");
        menuUsuario.add(menuUsuarioConta);

        menuUsuarioSair.setText("Sair");
        menuUsuarioSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsuarioSairActionPerformed(evt);
            }
        });
        menuUsuario.add(menuUsuarioSair);

        menuBar.add(menuUsuario);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(800, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuUsuarioSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsuarioSairActionPerformed
        dispose();
        new ViewLogin();
    }//GEN-LAST:event_menuUsuarioSairActionPerformed

    private void midiaHomeJumbotronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midiaHomeJumbotronActionPerformed
            new ViewMidiaHomeJumbotron().setVisible(true);
    }//GEN-LAST:event_midiaHomeJumbotronActionPerformed

    private void menuCadastrarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_menuCadastrarItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadastrarItemStateChanged

    private void menuCadastrarAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarAdministradorActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_menuCadastrarAdministradorActionPerformed

    private void menuCadastrarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarAlunoActionPerformed
        new ViewCadastroAluno().setVisible(true); 
    }//GEN-LAST:event_menuCadastrarAlunoActionPerformed
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuCadastrar;
    private javax.swing.JMenuItem menuCadastrarAdministrador;
    private javax.swing.JMenuItem menuCadastrarAluno;
    private javax.swing.JMenu menuMidia;
    private javax.swing.JMenu menuMidiaHome;
    private javax.swing.JMenu menuUsuario;
    private javax.swing.JMenu menuUsuarioConta;
    private javax.swing.JMenuItem menuUsuarioSair;
    private javax.swing.JMenuItem midiaHomeCarrossel;
    private javax.swing.JMenuItem midiaHomeGaleria;
    private javax.swing.JMenuItem midiaHomeJumbotron;
    // End of variables declaration//GEN-END:variables

}
