-- MySQL Script generated by MySQL Workbench
-- Mon Jul 27 10:43:26 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cl19467
-- -----------------------------------------------------
/*DROP SCHEMA IF EXISTS `cl19467` ;*/

-- -----------------------------------------------------
-- Schema cl19467
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cl19467` DEFAULT CHARACTER SET utf8 ;
USE `cl19467` ;

-- -----------------------------------------------------
-- Table `cl19467`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cl19467`.`admin`;

CREATE TABLE IF NOT EXISTS `cl19467`.`admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cl19467`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cl19467`.`usuario` ;

CREATE TABLE IF NOT EXISTS `cl19467`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ra` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NULL,
  `picture` TINYINT NOT NULL,
  `created` VARCHAR(45) NOT NULL,
  `updated` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ra_UNIQUE` (`ra` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cl19467`.`senha`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cl19467`.`senha` ;

CREATE TABLE IF NOT EXISTS `cl19467`.`senha` (
  `usuario_id` INT NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`usuario_id`),
  CONSTRAINT `fk_senha_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `cl19467`.`usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cl19467`.`senha_reset`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cl19467`.`senha_reset` ;

CREATE TABLE IF NOT EXISTS `cl19467`.`senha_reset` (
  `usuario_id` INT NOT NULL,
  `selector` TEXT NOT NULL,
  `token` LONGTEXT NOT NULL,
  `expire` VARCHAR(45) NULL,
  PRIMARY KEY (`usuario_id`),
  CONSTRAINT `fk_senha_reset_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `cl19467`.`usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cl19467`.`time`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cl19467`.`time` ;

CREATE TABLE IF NOT EXISTS `cl19467`.`time` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_idx` (`usuario_id` ASC),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC),
  CONSTRAINT `fk_time_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `cl19467`.`usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cl19467`.`usuario_time`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cl19467`.`usuario_time` ;

CREATE TABLE IF NOT EXISTS `cl19467`.`usuario_time` (
  `time_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`time_id`, `usuario_id`),
  INDEX `fk_usuario_idx` (`usuario_id` ASC),
  INDEX `fk_time_idx` (`time_id` ASC),
  CONSTRAINT `fk_usuario_time_time`
    FOREIGN KEY (`time_id`)
    REFERENCES `cl19467`.`time` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_usuario_time_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `cl19467`.`usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cl19467`.`modalidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cl19467`.`modalidade` ;

CREATE TABLE IF NOT EXISTS `cl19467`.`modalidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cl19467`.`ano`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cl19467`.`ano` ;

CREATE TABLE IF NOT EXISTS `cl19467`.`ano` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ano` YEAR NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cl19467`.`edicao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cl19467`.`edicao` ;

CREATE TABLE IF NOT EXISTS `cl19467`.`edicao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ano_id` INT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `ano_id`),
  INDEX `fk_edicao_ano_idx` (`ano_id` ASC),
  CONSTRAINT `fk_edicao_ano`
    FOREIGN KEY (`ano_id`)
    REFERENCES `cl19467`.`ano` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cl19467`.`modalidade_edicao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cl19467`.`modalidade_edicao` ;

CREATE TABLE IF NOT EXISTS `cl19467`.`modalidade_edicao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `edicao_id` INT NOT NULL,
  `modalidade_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_edicao_idx` (`edicao_id` ASC),
  INDEX `fk_modalidade_idx` (`modalidade_id` ASC),
  UNIQUE INDEX `fk_edicao_modalidade_unique` (`edicao_id` ASC, `modalidade_id` ASC),
  CONSTRAINT `fk_modalidade_edicao_modalidade`
    FOREIGN KEY (`modalidade_id`)
    REFERENCES `cl19467`.`modalidade` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_modalidade_edicao_edicao`
    FOREIGN KEY (`edicao_id`)
    REFERENCES `cl19467`.`edicao` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cl19467`.`partida`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cl19467`.`partida` ;

CREATE TABLE IF NOT EXISTS `cl19467`.`partida` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `modalidade_edicao_id` INT NOT NULL,
  `data` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_partida_modalidade_edicao1_idx` (`modalidade_edicao_id` ASC),
  CONSTRAINT `fk_partida_modalidade_edicao`
    FOREIGN KEY (`modalidade_edicao_id`)
    REFERENCES `cl19467`.`modalidade_edicao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cl19467`.`modalidade_edicao_time`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cl19467`.`modalidade_edicao_time` ;

CREATE TABLE IF NOT EXISTS `cl19467`.`modalidade_edicao_time` (
  `modalidade_edicao_id` INT NOT NULL,
  `time_id` INT NOT NULL,
  `ativo` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`modalidade_edicao_id`, `time_id`),
  INDEX `fk_modalidade_edicao_idx` (`time_id` ASC),
  INDEX `fk_time_idx` (`modalidade_edicao_id` ASC),
  CONSTRAINT `fk_modalidade_edicao_time_modalidade_edicao`
    FOREIGN KEY (`modalidade_edicao_id`)
    REFERENCES `cl19467`.`modalidade_edicao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_modalidade_edicao_time_time`
    FOREIGN KEY (`time_id`)
    REFERENCES `cl19467`.`time` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cl19467`.`partida_times`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cl19467`.`partida_times` ;

CREATE TABLE IF NOT EXISTS `cl19467`.`partida_times` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `partida_id` INT NOT NULL,
  `pontuacao` INT NOT NULL DEFAULT 0,
  `modalidade_edicao_time_id` INT NOT NULL,
  PRIMARY KEY (`id`, `modalidade_edicao_time_id`),
  INDEX `fk_modalidade_edicao_time_idx` (`modalidade_edicao_time_id` ASC),
  CONSTRAINT `fk_partida_times_partida`
    FOREIGN KEY (`partida_id`)
    REFERENCES `cl19467`.`partida` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_partida_times_modalidade_edicao_time`
    FOREIGN KEY (`modalidade_edicao_time_id`)
    REFERENCES `cl19467`.`modalidade_edicao_time` (`time_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- INSERTS INICIAIS
-- -----------------------------------------------------
INSERT INTO `cl19467`.`admin` (`usuario`, `senha`) VALUES ('admin', '21232f297a57a5a743894a0e4a801fc3');