-- MySQL Script generated by MySQL Workbench
-- Wed May 27 00:04:29 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tcc` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tcc` DEFAULT CHARACTER SET utf8 ;
USE `tcc` ;

-- -----------------------------------------------------
-- Table `HA_carrossel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HA_carrossel` (
  `HA_id` INT NOT NULL AUTO_INCREMENT,
  `HA_status` TINYINT NOT NULL DEFAULT 0,
  `HA_imagem` LONGBLOB NULL,
  `HA_imagemalt` VARCHAR(45) NULL,
  `HA_legendatitulo` VARCHAR(100) NULL,
  `HA_legendatexto` MEDIUMTEXT NULL,
  PRIMARY KEY (`HA_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HB_jumbotron`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HB_jumbotron` (
  `HB_id` INT NOT NULL,
  `HB_status` TINYINT(1) NULL DEFAULT 1,
  `HB_titulo` VARCHAR(45) NULL DEFAULT NULL,
  `HB_subtitulo` VARCHAR(256) NULL DEFAULT NULL,
  `HB_texto` MEDIUMTEXT NULL DEFAULT NULL,
  `HB_textobotao` VARCHAR(25) NULL DEFAULT NULL,
  PRIMARY KEY (`HB_id`),
  UNIQUE INDEX `HB_status_UNIQUE` (`HB_status` ASC))
ENGINE = InnoDB;

INSERT INTO `HB_jumbotron` (`HB_id`, `HB_status`, `HB_titulo`, `HB_subtitulo`, `HB_texto`, `HB_textobotao`) VALUES ('1', '1', 'teste', 'teste', 'teste', 'teste');


-- -----------------------------------------------------
-- Table `GA_galeria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GA_galeria` (
  `GA_id` INT NOT NULL AUTO_INCREMENT,
  `GA_midia` LONGBLOB NULL,
  `GA_titulo` VARCHAR(45) NULL,
  `GA_subtitulo` VARCHAR(256) NULL,
  `GA_descricao` MEDIUMTEXT NULL,
  `GA_data` DATE NULL,
  PRIMARY KEY (`GA_id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `DA_admin`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `DA_admin` (
  `DA_id` INT NOT NULL AUTO_INCREMENT,
  `DA_usuario` VARCHAR(20) NOT NULL,
  `DA_senha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`DA_id`))
ENGINE = InnoDB;

INSERT INTO `DA_admin` (`DA_usuario`, `DA_senha`) VALUES ('admin', '21232f297a57a5a743894a0e4a801fc3');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
