-- MySQL Script generated by MySQL Workbench
-- Mon May 11 22:11:40 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`HA_carrossel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`HA_carrossel` (
  `HA_id` INT NOT NULL AUTO_INCREMENT,
  `HA_status` TINYINT NOT NULL DEFAULT 0,
  `HA_imagem` LONGBLOB NULL,
  `HA_imagemalt` VARCHAR(45) NULL,
  `HA_legendatitulo` VARCHAR(100) NULL,
  `HA_legendatexto` MEDIUMTEXT NULL,
  PRIMARY KEY (`HA_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
