-- MySQL Script generated by MySQL Workbench
-- Mon May 11 22:05:26 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cl19467
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cl19467
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cl19467` DEFAULT CHARACTER SET utf8 ;
USE `cl19467` ;

-- -----------------------------------------------------
-- Table `cl19467`.`HB_jumbotron`
-- -----------------------------------------------------
CREATE TABLE `HB_jumbotron` (
  `HB_id` int(11) NOT NULL AUTO_INCREMENT,
  `HB_status` tinyint(1) DEFAULT NULL,
  `HB_titulo` varchar(45) DEFAULT NULL,
  `HB_subtitulo` varchar(256) DEFAULT NULL,
  `HB_texto` mediumtext,
  `HB_textobotao` varchar(25) DEFAULT NULL,
  PRIMARY KEY (`HB_id`),
  UNIQUE KEY `HB_status_UNIQUE` (`HB_status`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
