-- MySQL Script generated by MySQL Workbench
-- Mon May 11 22:05:26 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`HB_jumbotron`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`HB_jumbotron` (
  `HB_id` INT NOT NULL AUTO_INCREMENT,
  `HB_status` TINYINT NOT NULL DEFAULT 1,
  `HB_titulo` VARCHAR(45) NULL,
  `HB_subtitulo` VARCHAR(256) NULL,
  `HB_texto` MEDIUMTEXT NULL,
  `HB_textobotao` VARCHAR(25) NULL,
  PRIMARY KEY (`HB_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
