/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.dao.EdicaoDAO;
import model.dao.ModalidadeDAO;
import model.dao.ModalidadeEdicaoDAO;
import model.dao.StatusModalidadeEdicaoDAO;
import model.domain.Edicao;
import model.domain.Modalidade;
import model.domain.ModalidadeEdicao;
import model.domain.StatusModalidadeEdicao;

/**
 *
 * @author lgpc1
 */
public class ViewCadastroModalidadeEdicao extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewCadastrarAno
     */
    public ViewCadastroModalidadeEdicao() {
        initComponents();
        readjTable();
        
        //para preencher o combo box da modalidade
        ModalidadeDAO mdao = new ModalidadeDAO();
        for(Modalidade m: mdao.read()){
            jcbModalidade.addItem(m);
        }
        
        //para preencher o combo box status
        StatusModalidadeEdicaoDAO sdao = new StatusModalidadeEdicaoDAO();
        for(StatusModalidadeEdicao s: sdao.read()){
            jcbStatus.addItem(s);
        }
        
        EdicaoDAO edao = new EdicaoDAO();
        for(Edicao e: edao.read()){
            jbcEdicao.addItem(e);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbModalidade = new javax.swing.JComboBox<>();
        jcbAtivar = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jcbStatus = new javax.swing.JComboBox<>();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jbcEdicao = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de Modalidade por Edição"));

        jLabel1.setText("Edição:");

        jLabel2.setText("Modalidade:");

        jcbAtivar.setText("Ativar");

        jLabel3.setText("Status:");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbModalidade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcbStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 299, Short.MAX_VALUE)
                        .addComponent(btnExcluir))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbAtivar)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jbcEdicao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbcEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbModalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcbAtivar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnExcluir))
                .addContainerGap())
        );

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "EDICAO", "MODALIDADE", "STATUS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        Modalidade modalidade = (Modalidade) jcbModalidade.getSelectedItem();
        StatusModalidadeEdicao statusModalidadeEdicao = (StatusModalidadeEdicao) jcbStatus.getSelectedItem();
        Edicao edicao = (Edicao) jbcEdicao.getSelectedItem();
        if(jcbAtivar.isSelected()){
            ModalidadeEdicao me = new ModalidadeEdicao();
            ModalidadeEdicaoDAO dao = new ModalidadeEdicaoDAO();
            me.setEdicao(edicao.getId());
            me.setModalidade(modalidade.getId());
            me.setStatus(statusModalidadeEdicao.getId());
            me.setAtivar(1);
            dao.create(me);
            readjTable();
        }
        else{
            ModalidadeEdicao me = new ModalidadeEdicao();
            ModalidadeEdicaoDAO dao = new ModalidadeEdicaoDAO();  
            me.setEdicao(edicao.getId());
            me.setModalidade(modalidade.getId());
            me.setStatus(statusModalidadeEdicao.getId());
            me.setAtivar(0);
            dao.create(me);
            readjTable();
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        if (jTable.getSelectedRow() != -1){
            
        ModalidadeEdicao t = new ModalidadeEdicao();
        ModalidadeEdicaoDAO dao = new ModalidadeEdicaoDAO();
            
            t.setId((int) jTable.getValueAt(jTable.getSelectedRow(), 0));
            
            dao.delete(t);
            
        //limpar os campos
    
            readjTable();
        }   
    }//GEN-LAST:event_btnExcluirActionPerformed

         public void readjTable(){
        DefaultTableModel modelo = (DefaultTableModel) jTable.getModel();
        modelo.setNumRows(0);
        ModalidadeEdicaoDAO cdao = new ModalidadeEdicaoDAO();
        
        for (ModalidadeEdicao c : cdao.read()) {
            
            modelo.addRow(new Object[]{
                c.getEdicao(),
                c.getModalidade(),
                c.getStatus(),
                c.getAtivar()
            });
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JComboBox<Object> jbcEdicao;
    private javax.swing.JCheckBox jcbAtivar;
    private javax.swing.JComboBox<Object> jcbModalidade;
    private javax.swing.JComboBox<Object> jcbStatus;
    // End of variables declaration//GEN-END:variables
}
