/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import control.HomeJumbotron;
import java.awt.Color;
import javax.swing.JOptionPane;
import model.domain.HomeJumbotronModel;

/**
 *
 * @author lgpc1
 */
public class ViewMidiaHomeJumbotron extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewMidiaHomeJumbotron
     */
    
    public ViewMidiaHomeJumbotron() {
        initComponents();
        
        loadJumbotronViewData();
    }
    
    private void loadJumbotronViewData(){
        HomeJumbotronModel jumbotron = HomeJumbotron.loadJumbotron();
        
        this.txtTitulo.setText(jumbotron.getTitulo());
        this.txtSubtitulo.setText(jumbotron.getSubtitulo());
        this.txtTexto.setText(jumbotron.getTexto());
        this.txtTextoBotao.setText(jumbotron.getTextoBotao());
       
        if(jumbotron.getStatus() == 1){
            this.status.setText("Ativo.");
            this.status.setForeground(Color.green);
            this.cbJumbotronStatus.setSelected(true);
        }else{
            this.status.setText("Desativado.");
            this.status.setForeground(Color.red);
            this.cbJumbotronStatus.setSelected(false);
        }
        
        if(jumbotron.getStatusBotao() == 1){
            this.cbBotaoStatus.setSelected(true);
        }else{
            this.cbBotaoStatus.setSelected(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlEditarJumbotron = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        lblSubtitulo = new javax.swing.JLabel();
        txtSubtitulo = new javax.swing.JTextField();
        lblTexto = new javax.swing.JLabel();
        txtScrollPanel = new javax.swing.JScrollPane();
        txtTexto = new javax.swing.JTextArea();
        lblTextoBotao = new javax.swing.JLabel();
        txtTextoBotao = new javax.swing.JTextField();
        cbBotaoStatus = new javax.swing.JCheckBox();
        lblStatus = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        cbJumbotronStatus = new javax.swing.JCheckBox();
        btnSalvar = new javax.swing.JButton();

        setClosable(true);

        pnlEditarJumbotron.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Editar Jumbotron da Página Principal", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        lblTitulo.setText("Título:");

        lblSubtitulo.setText("Subtitulo:");

        lblTexto.setText("Texo:");

        txtTexto.setColumns(20);
        txtTexto.setRows(5);
        txtScrollPanel.setViewportView(txtTexto);

        lblTextoBotao.setText("Botão:");

        cbBotaoStatus.setText("Botão Ativo");

        javax.swing.GroupLayout pnlEditarJumbotronLayout = new javax.swing.GroupLayout(pnlEditarJumbotron);
        pnlEditarJumbotron.setLayout(pnlEditarJumbotronLayout);
        pnlEditarJumbotronLayout.setHorizontalGroup(
            pnlEditarJumbotronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditarJumbotronLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEditarJumbotronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblTextoBotao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSubtitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlEditarJumbotronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEditarJumbotronLayout.createSequentialGroup()
                        .addGroup(pnlEditarJumbotronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                            .addComponent(txtSubtitulo)
                            .addComponent(txtScrollPanel))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlEditarJumbotronLayout.createSequentialGroup()
                        .addComponent(txtTextoBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbBotaoStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlEditarJumbotronLayout.setVerticalGroup(
            pnlEditarJumbotronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditarJumbotronLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEditarJumbotronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlEditarJumbotronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubtitulo)
                    .addComponent(txtSubtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlEditarJumbotronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTexto)
                    .addComponent(txtScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlEditarJumbotronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTextoBotao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTextoBotao)
                    .addComponent(cbBotaoStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        lblStatus.setText("Jumbotron status:");

        cbJumbotronStatus.setText("Jumbotron Ativo");

        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                        .addComponent(cbJumbotronStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlEditarJumbotron, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(status)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlEditarJumbotron, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus)
                    .addComponent(status))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbJumbotronStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        HomeJumbotronModel jumbotron = new HomeJumbotronModel();
        
        jumbotron.setStatus(this.cbJumbotronStatus.isSelected() ? 1 : 0);
        jumbotron.setTitulo(this.txtTitulo.getText());
        jumbotron.setSubtitulo(this.txtSubtitulo.getText());
        jumbotron.setTexto(this.txtTexto.getText());
        jumbotron.setStatusBotao(this.cbBotaoStatus.isSelected() ? 1 : 0);
        jumbotron.setTextoBotao(this.txtTextoBotao.getText());
        
        Boolean result = HomeJumbotron.saveJumbotron(jumbotron);
        
        if(result){
            JOptionPane.showMessageDialog(this, "Jumbotron alterado com sucesso!", "Mensagem", WIDTH);
        }else{
            JOptionPane.showMessageDialog(this, "Falha ao alterar jumbotron", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        loadJumbotronViewData();
    }//GEN-LAST:event_btnSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JCheckBox cbBotaoStatus;
    private javax.swing.JCheckBox cbJumbotronStatus;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblTexto;
    private javax.swing.JLabel lblTextoBotao;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlEditarJumbotron;
    private javax.swing.JLabel status;
    private javax.swing.JScrollPane txtScrollPanel;
    private javax.swing.JTextField txtSubtitulo;
    private javax.swing.JTextArea txtTexto;
    private javax.swing.JTextField txtTextoBotao;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
